#pragma once
#define GRAPHS_H

int DegreesOfGraphVertices();
int EdgeListGraph();
int GraphByAdjacencyMatrix();
int LoopsAndMultipleEdgesInGraph();
int PlantForest();
int CargoTransportation();
int FriendsOfFriends();
int CellRemoval();
int EncyclopediaOfSimpleGraphs();
int Lines();
int NumberOfHamiltonianPaths();
int FlightsInTime();
int Spellstorm();
int Shiriivuk();
int PiggyBack();
int PureDijkstra();