#pragma once
#define DYNAMICPROGRAMMING_H

int ClassicFibonacciNumbers_2();
int Problem2_3Stairs();
int Hike();
int ThreeOnesInRow();
int Turtle_2();
int KnightsMove();
int KnightsMove_2();
int OrangeAppleBanana_2();
int Calculator();
int SmoothNumbers();
int Knapsack();
int MaxSubpalindrome();
int Data2ItemSets();
int ColoredBowling();
int LargestIncreasingSubsequence();
int LargestCommonSubsequence();
int EditorialDistance_1();
int EditorialDistance_2();